name: BackPack
version: '${project.version}'
main: ch.ksrminecraft.backpack.BackPack
api-version: '1.20'
commands:
  backpack:
    description: Öffnet ein gemeinsames Inventar für alle Spieler auf dem Server
    aliases: [bp]
